const FLIGHT_API_CALL_REQUEST = "FLIGHT_API_CALL_REQUEST";
const FLIGHT_API_CALL_SUCCESS = "FLIGHT_API_CALL_SUCCESS";
const FLIGHT_API_CALL_FAILURE = "FLIGHT_API_CALL_FAILURE";
const FLIGHT_API_CALL_REQUEST_POST = "FLIGHT_API_CALL_REQUEST_POST";
const FLIGHT_API_CALL_REQUEST_UPDATE = "FLIGHT_API_CALL_REQUEST_UPDATE";
const FLIGHT_API_CALL_REQUEST_DELETE = "FLIGHT_API_CALL_REQUEST_DELETE";
export {
    FLIGHT_API_CALL_REQUEST,
    FLIGHT_API_CALL_SUCCESS,
    FLIGHT_API_CALL_FAILURE,
    FLIGHT_API_CALL_REQUEST_POST,
    FLIGHT_API_CALL_REQUEST_UPDATE,
    FLIGHT_API_CALL_REQUEST_DELETE
}